# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers_adherents', '0008_wrongnumber'),
        ('phoning', '0005_auto_20160525_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='targets_with_wrong_number',
            field=models.ManyToManyField(blank=True, related_name='operations_where_wrong_number_found', to='fichiers_adherents.Adherent'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operation',
            name='targets_called_successfully',
            field=models.ManyToManyField(blank=True, related_name='operations_where_called', to='fichiers_adherents.Adherent'),
        ),
    ]
